project_id = "hmjwfnsygwzijjgrygia"

[functions.notify-lottery-winners]
verify_jwt = false

[functions.resend-api-test]
verify_jwt = false

[functions.simple-email-test]
verify_jwt = false

[functions.debug-lucky-dip-email]
verify_jwt = false

[functions.simple-email-test]
verify_jwt = false

[functions.test-lucky-dip-winners]
verify_jwt = false

[functions.resend-debug-test]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[functions.create-lottery-payment]
verify_jwt = false

[functions.create-lottery-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.get-lottery-users]
verify_jwt = false

[functions.delete-lottery-user]
verify_jwt = false

[functions.conduct-lottery-draw]
verify_jwt = false

[functions.process-draw-completion]
verify_jwt = false

[functions.send-lottery-purchase-email]
verify_jwt = false

[functions.send-lottery-subscription-email]
verify_jwt = false

[functions.send-test-emails]
verify_jwt = false

[functions.get-subscription-details]
verify_jwt = false

[functions.process-lottery-purchase]
verify_jwt = false

[functions.get-user-emails]
verify_jwt = false

[functions.trigger-live-draw]
verify_jwt = false

[functions.get-admin-users]
verify_jwt = false

[functions.invite-admin-user]
verify_jwt = false

[functions.upload-to-cloudinary]
verify_jwt = false