INSERT INTO public.players (name, club, position, heritage, team) VALUES
('Aaron Williams', NULL, 'Forwards', 'German', 'heritage'),
('Alex Land', 'Featherston Lions', 'Forwards', 'British', 'heritage'),
('Bailey Ellis', NULL, 'Backs', 'British', 'heritage'),
('Connor Hampson', 'Featherston Lions', 'Forwards', 'German', 'heritage'),
('Charlie Tetley', 'Oulton Raiders', 'Forwards', 'German', 'heritage'),
('Dylan Burdorf', 'German Exiles', 'Backs', 'German', 'heritage'),
('Jamie Blakestone', NULL, 'Forwards', 'British', 'heritage'),
('Jay Kay', 'Thornhill Trojans', 'Backs', 'German', 'heritage'),
('Jimmy Adams', 'Army/REME', 'Backs', 'German', 'heritage'),
('Josh McConnell', 'Wath Brow Hornets', 'Utility', 'German', 'heritage'),
('Lewis Dempsey', NULL, 'Backs', 'British', 'heritage'),
('Lewis Wilson', 'Bentley', 'Backs', 'British', 'heritage'),
('Liam Harley', 'Dewsbury Celtic', 'Forwards', 'British', 'heritage'),
('Martin Robinson', 'Sharlston Rovers', 'Utility', 'British', 'heritage'),
('Scott Wilson', NULL, 'Forwards', 'British', 'heritage'),
('Shaun Smith', 'Crigglestone All Blacks', 'Forwards', 'German', 'heritage'),
('William Fairhead', NULL, 'Forwards', 'British', 'heritage'),
('Zach Burke', 'Knottingly Mustangs', 'Backs', 'British', 'heritage'),
('Tom Hughes', 'German Exiles', 'Utility', 'British', 'heritage'),
('James Whitaker', NULL, 'Forwards', 'British', 'heritage'),
('Mikey Greensmith', 'Thornhill Trojans', 'Forwards', 'British', 'heritage');